'use client';

import React, { useState, useEffect, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useAuth } from '../../lib/auth/auth-context';
import { apiClient } from '../../lib/api/client';
import { useToast } from '../../components/ui/Toast';
import { Button } from '../../components/ui/Button';
import { Input } from '../../components/ui/Input';
import { KeyRound, ShieldAlert, CheckCircle2, ArrowLeft, Layers } from 'lucide-react';
import Link from 'next/link';

function ResetPasswordContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const tokenFromUrl = searchParams.get('token');
  const isMandatory = searchParams.get('mandatory') === 'true';

  const { user, refreshUser, isAuthenticated } = useAuth();
  const { showToast } = useToast();

  const [mode, setMode] = useState<'reset' | 'request'>(
    tokenFromUrl || isMandatory || isAuthenticated ? 'reset' : 'request',
  );

  const [currentPassword, setCurrentPassword] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [requestEmail, setRequestEmail] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);

  // If user is SYSTEM_GENERATED, show clear restriction banner
  const isSystemGenerated = user?.creationType === 'SYSTEM_GENERATED';

  const handleResetPassword = async (e: React.FormEvent) => {
    e.preventDefault();
    if (newPassword !== confirmPassword) {
      showToast('New passwords do not match', 'error');
      return;
    }
    if (newPassword.length < 8) {
      showToast('New password must be at least 8 characters long', 'error');
      return;
    }

    setIsLoading(true);
    try {
      await apiClient.post('/auth/reset-password', {
        token: tokenFromUrl || undefined,
        currentPassword: currentPassword || undefined,
        newPassword,
      });

      setIsSuccess(true);
      showToast('Password updated successfully!', 'success');
      await refreshUser();

      setTimeout(() => {
        router.push('/dashboard');
      }, 1500);
    } catch (err: any) {
      showToast(err.message || 'Failed to update password', 'error');
    } finally {
      setIsLoading(false);
    }
  };

  const handleRequestReset = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!requestEmail) {
      showToast('Please enter your email', 'error');
      return;
    }

    setIsLoading(true);
    try {
      const res = await apiClient.post<any>('/auth/forgot-password', {
        email: requestEmail,
      });
      setIsSuccess(true);
      showToast(res.message || 'Reset link sent if account exists', 'success');
    } catch (err: any) {
      showToast(err.message || 'Failed to request reset', 'error');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#F7F7F5] flex flex-col justify-center items-center p-4 sm:p-6">
      <div className="w-full max-w-sm">
        {/* Brand Header */}
        <div className="text-center mb-6">
          <div className="w-10 h-10 rounded-lg bg-slate-900 text-white flex items-center justify-center mx-auto mb-2.5 shadow-xs">
            <KeyRound className="w-5 h-5" />
          </div>
          <h1 className="text-xl font-bold text-slate-900 tracking-tight">
            {isMandatory ? 'Setup Permanent Password' : mode === 'reset' ? 'Set New Password' : 'Reset Password'}
          </h1>
          <p className="text-xs text-slate-500 mt-1">
            {isMandatory
              ? 'Please configure a new permanent password before accessing the system.'
              : mode === 'reset'
              ? 'Enter your new credentials below.'
              : 'Enter your email to receive a password reset link.'}
          </p>
        </div>

        {/* Form Card */}
        <div className="bg-white p-6 sm:p-7 rounded-xl border border-[#E7E7E3] shadow-card">
          {isSystemGenerated ? (
            <div className="text-center py-3">
              <div className="w-10 h-10 rounded-lg bg-amber-50 text-amber-700 border border-amber-200 flex items-center justify-center mx-auto mb-2.5">
                <ShieldAlert className="w-5 h-5" />
              </div>
              <h3 className="text-sm font-bold text-slate-900 mb-1">Password Change Blocked</h3>
              <p className="text-xs text-amber-800 leading-relaxed mb-5">
                Your account (<span className="font-mono font-semibold">{user?.email}</span>) was system-generated by SuperAdmin. In accordance with system security policy, system-generated accounts cannot change or reset passwords directly.
              </p>
              <Link href="/dashboard">
                <Button variant="primary" size="sm" className="w-full">
                  Return to Dashboard
                </Button>
              </Link>
            </div>
          ) : isSuccess ? (
            <div className="text-center py-3">
              <div className="w-10 h-10 rounded-lg bg-emerald-50 text-emerald-700 border border-emerald-200 flex items-center justify-center mx-auto mb-2.5">
                <CheckCircle2 className="w-5 h-5" />
              </div>
              <h3 className="text-sm font-bold text-slate-900 mb-1">
                {mode === 'reset' ? 'Password Updated' : 'Instructions Dispatched'}
              </h3>
              <p className="text-xs text-slate-500 mb-5">
                {mode === 'reset'
                  ? 'Redirecting to your dashboard...'
                  : 'Check your email inbox for instructions on resetting your password.'}
              </p>
              <Link href="/login">
                <Button variant="primary" size="sm" className="w-full">
                  Proceed to Sign In
                </Button>
              </Link>
            </div>
          ) : mode === 'reset' ? (
            <form onSubmit={handleResetPassword} className="space-y-4">
              {isMandatory && (
                <Input
                  label="Temporary Password *"
                  type="password"
                  placeholder="Enter temporary password"
                  value={currentPassword}
                  onChange={(e) => setCurrentPassword(e.target.value)}
                  required
                />
              )}

              <Input
                label="New Password *"
                type="password"
                placeholder="At least 8 characters"
                value={newPassword}
                onChange={(e) => setNewPassword(e.target.value)}
                required
              />

              <Input
                label="Confirm New Password *"
                type="password"
                placeholder="Re-enter new password"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                required
              />

              <Button
                variant="primary"
                size="md"
                type="submit"
                isLoading={isLoading}
                className="w-full mt-1"
              >
                {isMandatory ? 'Set Password & Continue' : 'Update Password'}
              </Button>
            </form>
          ) : (
            <form onSubmit={handleRequestReset} className="space-y-4">
              <Input
                label="Account Email Address *"
                type="email"
                placeholder="name@company.com"
                value={requestEmail}
                onChange={(e) => setRequestEmail(e.target.value)}
                required
              />

              <Button
                variant="primary"
                size="md"
                type="submit"
                isLoading={isLoading}
                className="w-full mt-1"
              >
                Send Reset Link
              </Button>
            </form>
          )}

          <div className="mt-5 pt-3.5 border-t border-slate-100 text-center">
            <Link
              href="/login"
              className="inline-flex items-center gap-1.5 text-xs text-slate-500 hover:text-slate-800 transition font-medium"
            >
              <ArrowLeft className="w-3.5 h-3.5" />
              Back to Sign In
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function ResetPasswordPage() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-[#F7F7F5]" />}>
      <ResetPasswordContent />
    </Suspense>
  );
}
